// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/index.css";
import { MSWProvider } from "@/components/MSWProvider";
import { AuthProvider } from "@/contexts/AuthContext"; // <-- ADD THIS IMPORT



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amplified",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider> {/* <-- WRAPPER START */}
          <MSWProvider>{children}</MSWProvider>
        </AuthProvider> {/* <-- WRAPPER END */}
      </body>
    </html>
  );
}