import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

const FAQ: React.FC = () => {
  const [openFAQ, setOpenFAQ] = useState<number | null>(0);

  const faqs = [
    {
      question: "Will this replace me as a tutor?",
      answer: "Absolutely not. AmplifiEd enhances your teaching by automating the repetitive tasks while keeping you in control. You remain the expert, the decision-maker, and the heart of the learning experience."
    },
    {
      question: "Who is AmplifiEd for?",
      answer: "Independent tutors, high school teachers, college instructors, and students preparing for exams. Anyone who wants to make teaching and learning more efficient and personalized."
    },
    {
      question: "How does AmplifiEd ensure content quality?",
      answer: "Every piece of content generated by AmplifiEd goes through your review and approval. The AI learns from your teaching style and preferences, ensuring all materials align with your standards and expertise."
    },
    {
      question: "What file formats do you support?",
      answer: "We support video recordings (MP4, MOV), audio files (MP3, WAV), and document uploads (PDF, DOCX). More formats are being added based on user feedback."
    },
    {
      question: "Is my data secure?",
      answer: "Yes. We use enterprise-grade security with end-to-end encryption. Your content and student data are never shared with third parties and are stored securely in compliance with educational privacy standards."
    },
    {
      question: "When will AmplifiEd be available?",
      answer: "We're currently in development with a planned release in Q2 2025. Early access users will get to try the platform first and help shape its features."
    }
  ];

  const toggleFAQ = (index: number) => {
    setOpenFAQ(openFAQ === index ? null : index);
  };

  return (
    <section id="faq" className="py-24 bg-slate-800/50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-400">
            Everything you need to know about AmplifiEd
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div 
              key={index}
              className="bg-slate-900/50 backdrop-blur-sm rounded-2xl border border-slate-700/50 overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full p-6 text-left flex items-center justify-between hover:bg-slate-800/30 transition-colors duration-200"
              >
                <h3 className="text-lg font-semibold text-white pr-4">
                  {faq.question}
                </h3>
                <div className="text-gray-400 flex-shrink-0">
                  {openFAQ === index ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                </div>
              </button>
              
              {openFAQ === index && (
                <div className="px-6 pb-6 animate-in slide-in-from-top duration-300">
                  <p className="text-gray-400 leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;